"""
Agent 2: SQL Generation Agent
================================
Converts a structured QueryIntent into a Snowflake SQL query.

Input  : QueryIntent (from Agent 1)
Output : SQL string targeting only approved secure views

The SQL is generated by Snowflake Cortex COMPLETE using a carefully
engineered prompt that includes schema context, business rules,
and strict guardrails against unsafe patterns.
"""

import re
from agents.query_understanding import QueryIntent
from services.snowflake_client import cortex_complete, DEFAULT_TENANT_ID
from config.prompts import SQL_GENERATION_PROMPT


def generate_sql(intent: QueryIntent, tenant_id: str = DEFAULT_TENANT_ID) -> str:
    """
    Generate SQL from a QueryIntent using Cortex COMPLETE.

    Returns the raw SQL string. The SQL is not yet validated — that
    happens in Agent 3 (sql_validator.py).
    """
    intent_json = intent.to_json()

    prompt = (
        SQL_GENERATION_PROMPT
        .replace("{intent_json}", intent_json)
        .replace("{tenant_id}", tenant_id)
    )

    raw = cortex_complete(prompt)

    # Clean up any markdown fencing
    sql = _clean_sql(raw)
    return sql


def _clean_sql(raw: str) -> str:
    """
    Strip markdown code blocks and leading/trailing whitespace from LLM output.
    Ensures the returned string is pure SQL.
    """
    # Remove ```sql ... ``` fences
    cleaned = re.sub(r"```(?:sql)?", "", raw, flags=re.IGNORECASE).strip()
    cleaned = cleaned.rstrip("`").strip()

    # Remove any explanatory text before the SELECT keyword
    select_match = re.search(r"\bSELECT\b", cleaned, re.IGNORECASE)
    if select_match:
        cleaned = cleaned[select_match.start():]

    # Collapse multiple blank lines
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)

    return cleaned.strip()
